# Generated by Django 4.2 on 2023-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tried', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
            ],
        ),
    ]
